defaults:
  - _self_
  - model: baseline

data:
  seq_len: 256
  num_tokens: 10000000
  batch_size: 64
  num_workers: 4
  pin_memory: true
train:
  epochs: 3
  log_interval: 200
  eval_iterations: 200
  use_wandb: true
  use_fp16: true