defaults:
  - _self_
  - model: baseline
  
data:
  seq_len: 256
  num_tokens: 50000
  batch_size: 64
  num_workers: 4
  pin_memory: true
train:
  epochs: 3
  log_interval: 50
  eval_iterations: 100
  use_wandb: true
  use_fp16: true
  grad_clip_model: none
  gra_clip_alphas: none
  watch_model: true
  train_router_steps: 0.5
dnas:
  capacity_ratio_search_space: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]